### ISSUE TITLE
Comments on smhifilter.sh

### ISSUE THREAD

**Issue by floridop** [Adib-Sh/MNXB11-homework#2]
This modification to my script:

https://github.com/Adib-Sh/MNXB11-homework/blob/db7623644405bb2d8bfb3a5ef2952fc6ee421112/homework4/smhifilter.sh#L47

Will cause the script to crash if there is no `output` folder exactly where the script is ran. If you plan to make a change don't leave it half-baked, you need to provide code so that your script can create the missing folder, OR give the user a hint of why the program crashes if the folder is not there. The following is the error shown when there is no `output` folder:

```shell
$ ./smhifilter.sh 
touch: cannot touch 'output/2024-11-03_smhifilter.sh.log': No such file or directory
cannot write logfile, exiting
```

When it comes to the filters you chose, well these are not really filters to me. Anyway let's say that the head filter picks the first 10 lines, that is fine for me.

But the other filter, the "sorted" one. Do you have any idea about *what* is being sorted and why? :)
let's look at the `tail` of the bare data file:
```shell
$ tail baredata_smhi-opendata_1_52230_20210906_212532.csv
2021-05-30 09:00:00 15.1 G
2021-05-30 12:00:00 16.4 G
2021-05-30 15:00:00 15.6 G
2021-05-30 18:00:00 13.2 G
2021-05-31 06:00:00 13.1 G
2021-05-31 09:00:00 16.1 G
2021-05-31 12:00:00 18.4 G
2021-05-31 15:00:00 20.1 G
2021-05-31 18:00:00 17.1 G
2021-06-01 06:00:00 13.9 G
```

And now the sorted output:
```shell
 $ cat sortedTail__filtered_smhi-opendata_1_52230_20210906_212532.csv 
2021-05-30 09:00:00 15.1 G
2021-05-30 12:00:00 16.4 G
2021-05-30 15:00:00 15.6 G
2021-05-30 18:00:00 13.2 G
2021-05-31 06:00:00 13.1 G
2021-05-31 09:00:00 16.1 G
2021-05-31 12:00:00 18.4 G
2021-05-31 15:00:00 20.1 G
2021-05-31 18:00:00 17.1 G
2021-06-01 06:00:00 13.9 G
```
mh, I have a suspicion here...

```shell
$ if diff <(tail baredata_smhi-opendata_1_52230_20210906_212532.csv) <(cat sortedTail__filtered_smhi-opendata_1_52230_20210906_212532.csv); then echo "No differences"; else "files differ"; fi
No differences
```

That's right. Sorting the tail does nothing. Why?

because sort is a simple program. Unless you tell it to do some specific sorting, the default is lexicographic sorting on the first element of a CSV with spaces. In short it's ordering the dates as if they were in alphabetical order. If you didn't know, this is a property of the data format in use in Sweden:

YYYY-MM-DD

can be sorted in lexicographical order  (that is, letters not numbers) and it will be also sorted in time. 

So running sort on the already ordered dates will show you the dates in the same order.

Is that what you had in mind? sort and already sorted set?

**Comment by Adib-Sh** [comment]
Thank you so much for your comments.
The separator is fixed. I added "," separator to the smhicleaner.sh.
Also, I added the condition for both smhicleaner.sh and smhifilter.sh to check if the output folder exists and create and new folder otherwise.
I additionally added a new filter which takes only the temperatures between 5 to 10 degrees.
