### ISSUE TITLE
Comments on smhicleaner.sh

### ISSUE THREAD

**Issue by floridop** [Adib-Sh/MNXB11-homework#3]
Nice that you attempted to fix the `output` folder issue. However, it's not very well done for several reasons:

1) output should intuitively contain output files, but it contains the `original...` file which is actually an input file
2) the actual output file `baredata...` is outside the folder because you forgot to add the `output/` prefix
3) creating a file in a place first and then moving it later should be avoided, as it may cause issues while the file is being processed. 
https://github.com/Adib-Sh/MNXB11-homework/blob/41a1e49a496d7afcf79e93646b830746e3ccaef8/homework4/smhicleaner.sh#L167-L169

For temporary files is better to use the bash command `mktemp`. But this was not your case.

This is a common error when dealing with folders and filenames and it's due to a bad practice of attaching paths and filenames in different places in the code.

The solution to that is to attach the folder name already when you define the filename, that is, in lines:
https://github.com/Adib-Sh/MNXB11-homework/blob/41a1e49a496d7afcf79e93646b830746e3ccaef8/homework4/smhicleaner.sh#L118-L119

Good job anyway!

**Comment by Adib-Sh** [comment]
Thank you so much for your comments Florido.
I will try to fix the issues you mentioned.
